# Generated by Django 2.1 on 2019-03-26 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blogs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentity',
            options={'ordering': ['-posted_since'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='blogentity',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='blogentity',
            name='readed_by',
        ),
        migrations.RemoveField(
            model_name='blogentity',
            name='subscribe_by',
        ),
        migrations.AddField(
            model_name='blogentity',
            name='posted_since',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 8, 44, 57, 207438), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='author',
            field=models.CharField(max_length=512, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='content',
            field=models.TextField(verbose_name='Полное руководство'),
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='header',
            field=models.CharField(max_length=512, verbose_name='Заголовок'),
        ),
    ]
