# Generated by Django 2.1 on 2019-03-26 01:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blogs_app', '0002_auto_20190326_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentity',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='posted_since',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 8, 50, 40, 810889), verbose_name='Дата публикации'),
        ),
    ]
