# Generated by Django 2.1 on 2019-03-26 02:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech_blogs_app', '0003_auto_20190326_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReadBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSubscribedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='content',
            field=models.TextField(verbose_name='Полное содержание записи'),
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='header',
            field=models.CharField(max_length=512, verbose_name='Заголовок записи'),
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='posted_since',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 9, 29, 0, 121791), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='blogsubscribedby',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_blogs_app.BlogEntity'),
        ),
        migrations.AddField(
            model_name='blogsubscribedby',
            name='subscribed_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogreadby',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_blogs_app.BlogEntity'),
        ),
        migrations.AddField(
            model_name='blogreadby',
            name='read_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
