# Generated by Django 2.1 on 2019-03-26 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech_blogs_app', '0004_auto_20190326_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogreadby',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogreadby',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='blogsubscribedby',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogsubscribedby',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogentity',
            name='posted_since',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 16, 9, 176333), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blogsubscribedby',
            name='subscribed_by',
            field=models.ManyToManyField(to='tech_blogs_app.BlogEntity'),
        ),
        migrations.DeleteModel(
            name='BlogReadBy',
        ),
    ]
