# Generated by Django 2.1 on 2019-03-26 09:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blogs_app', '0005_auto_20190326_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentity',
            name='posted_since',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 16, 39, 11, 493696), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blogsubscribedby',
            name='subscribed_by',
            field=models.ManyToManyField(related_name='sub', to=settings.AUTH_USER_MODEL),
        ),
    ]
